#logging.level.root = TRACE

# 서버 포트 설정
server:
  port: 9090

# database 연동 설정
spring:
  security:
    user:
      name: user
      password: 1230
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user1
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    #배포시 주의
    hibernate:
      ddl-auto: create


  application:
    name: kimpli
