#logging.level.root = TRACE

# ?? ?? ??
server:
  port: 9090

# database ?? ??
spring:
  security:
    user:
      name: user
      password: 1230
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user1
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      #?? ?? ?? ?? ???? ??? : create ?? update
      #??? ?? : update ?? validate
      ddl-auto: create

  # ?????? ??
  application:
    name: kimpli