#logging:
#  level:
#    root: TRACE

#logging:
#  level:
#    root: INFO
#  appenders:
#    - type: console
#      threshold: INFO
#      target: System.out
#      layout:
#        type: pattern
#        pattern: "%-5p %c{1}:%L - %m%n"

# 서버 포트 설정
server:
  servlet:
    session:
      timeout: 1800
    encoding:
      charset: utf-8
      force-response: true
  port: 9090



# 스프링 시큐리티 기본 계정 설정
spring:
  cors:
    allowed-origins: https://plikim.com
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  security:
    user:
      name: user
      password: 1230

  #database 연동 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.76.213/plikim?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: user1
    password: 1234

#  data:
#    mongodb:
#      host: 52.79.76.213
#      port: 27017
#      database: chatdb
#  data:
#    mongodb:
#      host: 52.79.76.213
#      port: 27017
#      authentication-database: admin
#      username: lee
#      password: 1230
#      authSource: chatdb

#  data:
#    mongodb:
#      host: 52.79.76.213
#      port: 27017
#      username: lee
#      password: 1230
#      authentication-database: admin
  data:
    mongodb:
      uri: mongodb://lee:1230@52.79.76.213:27017/chatdb?authSource=admin





  #thymeleaf
  thymeleaf:
    cache: false

  #spring data jpa 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  application:
    name: kimpli
    timezone: Asia/Seoul


#mybatiså
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eek.kimpli.member.dto
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true


systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true
  timeZoneInfo: Asia/Seoul


