#logging:
#  level:
#    root: TRACE

#logging:
#  level:
#    root: INFO
#  appenders:
#    - type: console
#      threshold: INFO
#      target: System.out
#      layout:
#        type: pattern
#        pattern: "%-5p %c{1}:%L - %m%n"

# 서버 포트 설정
server:
  port: 9090



# 스프링 시큐리티 기본 계정 설정
spring:
  security:
    user:
      name: user
      password: 1230
  #database 연동 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.76.213/plikim?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: user1
    password: 1234

  data:
    mongodb:
      host: 52.79.76.213
      port: 27017
      database: chatdb

  #thymeleaf
  thymeleaf:
    cache: false

  #spring data jpa 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  application:
    name: kimpli

#mybatiså
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eek.kimpli.member.dto
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true





